image:
  repository: <ECR-URL>
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_SECRET_KEY: "replace-me"
  DJANGO_DEBUG: "False"
  DB_HOST: "your-db-host"
  DB_PORT: "5432"
